package kr.or.connect.reservation.dao;

public class ReservationSqls {
	public static final String SELECT_CATEGORY = "SELECT count(*) count, category_id id, category.name FROM category, reservationdb.display_info, product where product.id = display_info.product_id and category.id = product.category_id group by product.category_id;";
	public static final String SELECT_PRODUCT_BY_CATEGORY = "select dinfo.id displayInfoId, prd.id productId, prd.description productDescription, prd.content productContent, dinfo.place_name, finfo.save_file_name productImageUrl from product prd, display_info dinfo, product_image img, file_info finfo where prd.id=dinfo.product_id and img.product_id = prd.id and img.type=\"th\" and img.file_id = finfo.id and prd.category_id=:category_id limit :start, :limit";
	public static final String SELECT_ALL_PRODUCT = "select dinfo.id displayInfoId, prd.id productId, prd.description productDescription, dinfo.place_name, prd.content productContent, finfo.save_file_name productImageUrl from product prd, display_info dinfo, product_image img, file_info finfo where prd.id=dinfo.product_id and img.product_id = prd.id and img.type=\"th\" and img.file_id = finfo.id limit :start, :limit ";
	public static final String SELECT_PROMOTION = "select promotion.id,product.id productId, file_info.save_file_name productImageUrl from promotion, product, product_image, file_info where promotion.product_id = product.id and product.id = product_image.product_id and product_image.file_id = file_info.id and product_image.type=\"th\"";
	public static final String SELECT_PROMOTION_BY_CATEGORY = "select promotion.id, product.id productId, file_info.save_file_name productImageUrl from promotion, product, product_image, file_info where promotion.product_id = product.id and product.id = product_image.product_id and product_image.file_id = file_info.id and product_image.type=\"th\" and product.category_id= :category_id";
}
